Shader "Custom/HueShift"
{
    //Generated by AI, with some edits by Dude of Dudovia to Allow for Saturation and Value to be controlled.
    Properties
    {
        _MainTex ("Texture", 2D) = "white" {}
        _Hue ("Hue Shift (0–1)", Range(0,1)) = 0
        _Sat ("Value (0–1)", Range(0,1)) = 1
        _Val ("SaturationYesItsSwitched (0–1)", Range(0,1)) = 1
    }

    SubShader
    {
        Tags { "RenderType"="Opaque" }
        LOD 100

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            sampler2D _MainTex;
            float _Hue;
            float _Sat;
            float _Val;

            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;
            };

            struct v2f
            {
                float2 uv : TEXCOORD0;
                float4 vertex : SV_POSITION;
            };

            v2f vert (appdata v)
            {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
                o.uv = v.uv;
                return o;
            }

            // RGB → HSV
            float3 rgb2hsv(float3 c)
            {
                float4 K = float4(0., -1./3., 2./3., -1.);
                float4 p = lerp(float4(c.bg, K.wz), float4(c.gb, K.xy), step(c.b, c.g));
                float4 q = lerp(float4(p.xyw, c.r), float4(c.r, p.yzx), step(p.x, c.r));

                float d = q.x - min(q.w, q.y);
                float e = 1e-10;
                return float3(abs(q.z + (q.w - q.y) / (6. * d + e)), d / (q.x + e), q.x);
            }

            // HSV → RGB
            float3 hsv2rgb(float3 c)
            {
                float4 K = float4(1., 2./3., 1./3., 3.);
                float3 p = abs(frac(c.xxx + K.xyz) * 6. - K.www);
                return c.z * lerp(K.xxx, saturate(p - K.xxx), c.y);
            }

            fixed4 frag (v2f i) : SV_Target
            {
                float4 col = tex2D(_MainTex, i.uv);

                float3 hsv = rgb2hsv(col.rgb);

                // Shift hue (wraps automatically)
                hsv.x = frac(hsv.x + _Hue);
                hsv.z = _Sat*0.2;
                hsv.y = _Val;

                col.rgb = hsv2rgb(hsv);

                return col;
            }
            ENDCG
        }
    }
}