using System;
using System.Globalization;
using System.Text.RegularExpressions;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.UIElements.Experimental;

public class NotificationWarningTimePreviewScript : MonoBehaviour
{
    public TMP_InputField TMP;
    public Slider NWTPS;
    public TimeControllerScript TCS;
    public int InvalidReset = 0;
    public void SetSlider()
    {
        try
        {
            Debug.Log("1");
            //if (ParseText(TMP.text) > NWTPS.maxValue) { NWTPS.maxValue = ParseText(TMP.text); Debug.Log("ew13"); }
            //else { NWTPS.maxValue = TCS.DefaultTime; Debug.Log("ew12"); }
            Debug.Log("2");
            NWTPS.value = ParseText(TMP.text);
            //NWTPS.value = float.Parse(TMP.text);
        }
        catch (Exception e) { Debug.Log(e); }//
    }
    public void UpdateSlider()
    {
        try
        {
            if (NWTPS.maxValue < TCS.DefaultTime) { NWTPS.maxValue = TCS.DefaultTime; Debug.Log("a1"); }
            TMP.text = (NWTPS.value.ToString());
            if (NWTPS.value > NWTPS.maxValue) { NWTPS.maxValue = NWTPS.value; Debug.Log("a2"); }
            else
            {
                Debug.Log(NWTPS.value);
                Debug.Log(NWTPS.maxValue);
                NWTPS.maxValue = TCS.DefaultTime;
                Debug.Log("a3");
            }
            TMP.text = ((int)NWTPS.value).ToString();
            if ((int)NWTPS.value == 0) { TMP.text = "0"; }
            if (TMP.text == "") { TMP.text = "0"; }
        }
        catch (Exception e) { Debug.Log(e); }//
    }
    public void Start()
    {
        UpdateSlider();
    }
    public float ParseText(string text)
    {
        try
        {
            Debug.Log(text);
            float HRegEx = 0;
            float MRegEx = 0;
            float SRegEx = 0;
            bool Multiple = false;
            string filteredspaces = Regex.Replace(text, @"\s+", "");
            string[] Times = filteredspaces.Split(':');
            //Regex Generated by AI, I can't write this nonsense.
            var match = Regex.Match(filteredspaces, @"(?i)(?:(-?\d*\.?\d+)h)?(?:(-?\d*\.?\d+)m)?(?:(-?\d*\.?\d+)s)?");
            float.TryParse(match.Groups[1].Value, NumberStyles.Any, CultureInfo.InvariantCulture, out HRegEx);
            float.TryParse(match.Groups[2].Value, NumberStyles.Any, CultureInfo.InvariantCulture, out MRegEx);
            float.TryParse(match.Groups[3].Value, NumberStyles.Any, CultureInfo.InvariantCulture, out SRegEx);
            if (Times.Length > 1)
                Multiple = true;
            if (Multiple)
            {
                Debug.Log("1");
                float timeadded = 0;
                for (int i = 0; i < Times.Length; i++)
                {

                    if (i == 0)
                    {
                        timeadded += float.Parse(Times[i]) * 60f;
                    }
                    if (i == 1)
                    {
                        timeadded += float.Parse(Times[i]);
                    }
                    if (i == 2)
                    {
                        timeadded += float.Parse(Times[i]) / 60f;
                    }
                }
                return timeadded;
            }
            else if (match.Length > 0)
            {
                Debug.Log("2");
                float timeadded = 0;
                timeadded += HRegEx * 60f;
                timeadded += MRegEx;
                timeadded += SRegEx / 60f;
                return timeadded;
            }
            else if (!Multiple)
            {
                Debug.Log("3");
                float timeadded = 0;
                timeadded += float.Parse(TMP.text, CultureInfo.InvariantCulture.NumberFormat);
                Debug.Log(timeadded);
                return timeadded;
            }
            
        }
        catch (Exception e)
        {
            { if (TMP.text != "") { TMP.text = "INVALID"; InvalidReset = 360; Debug.Log(e); } }
        }
        return 30;
    }
}
 