using System;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using TMPro;
using UnityEngine;

public class TimeAdder : MonoBehaviour
{

    public RectTransform RT;
    public TimeControllerScript TCS;
    public TMP_InputField TMP;
    public float value = 0;
    public GameObject StoreValues;
    public GameObject ViewportContent;
    public bool KPDown = false;
    public bool RTDown = false;
    public int InvaldidReset = 0;
    public string teststr;
    void Update()
    {
        RT.anchoredPosition = new Vector3(0, (-Screen.height) + Screen.height * value, 0);
        RT.localScale = new Vector3(Screen.height / 481.6f, Screen.height / 481.6f, Screen.height / 481.6f) * 1.3f;
        if (Input.GetKeyDown(KeyCode.KeypadEnter) && !KPDown) { KPDown = true; }
        if (Input.GetKeyDown(KeyCode.Return) && !RTDown) { RTDown = true; }
        if (Input.GetKeyUp(KeyCode.KeypadEnter)) { KPDown = false; }
        if (Input.GetKeyUp(KeyCode.Return)) { RTDown = false; }

        InvaldidReset--;
        if (InvaldidReset == 0 && TMP.text == "INVALID") { TMP.text = ""; }
    }
    public void StopEditing()
    {
        if (Input.GetKeyDown(KeyCode.KeypadEnter) && !KPDown) { KPDown = true; }
        if (Input.GetKeyDown(KeyCode.Return) && !RTDown) { RTDown = true; }
        if (KPDown || RTDown) { AppenedTime(); }
    }
    public void AppenedTime()
    {
        try
        {
            float HRegEx = 0;
            float MRegEx = 0;
            float SRegEx = 0;
            bool Multiple = false;
            string filteredspaces = Regex.Replace(TMP.text, @"\s+", "");
            string[] Times = filteredspaces.Split(':');
            //Regex Generated by AI, I can't write this nonsense.
            var match = Regex.Match(filteredspaces, @"(?i)(?:(-?\d*\.?\d+)h)?(?:(-?\d*\.?\d+)m)?(?:(-?\d*\.?\d+)s)?");
            float.TryParse(match.Groups[1].Value, NumberStyles.Any, CultureInfo.InvariantCulture, out HRegEx);
            float.TryParse(match.Groups[2].Value, NumberStyles.Any, CultureInfo.InvariantCulture, out MRegEx);
            float.TryParse(match.Groups[3].Value, NumberStyles.Any, CultureInfo.InvariantCulture, out SRegEx);
            if (Times.Length > 1)
                Multiple = true;
            if (Multiple)
            {
                float timeadded = 0;
                for (int i = 0; i < Times.Length; i++)
                {
                    
                    if (i == 0)
                    {
                        timeadded += float.Parse(Times[i]) * 60f;
                        TCS.UsedTime += timeadded;
                    }
                    if (i == 1)
                    {
                        timeadded += float.Parse(Times[i]);
                        TCS.UsedTime += timeadded;
                    }
                    if (i == 2)
                    {
                        timeadded += float.Parse(Times[i]) / 60f;
                        TCS.UsedTime += timeadded;
                    }
                }
                var logs = Instantiate(StoreValues, new Vector3(0, transform.position.y, 0), transform.rotation, ViewportContent.transform);
                logs.GetComponent<AddedTimesScript>().MinutesToAdd = timeadded;
                logs.GetComponent<AddedTimesScript>().BeingMade = true;
            }
            else if (match.Length > 0)
            {
                float timeadded = 0;
                timeadded += HRegEx * 60f;
                timeadded += MRegEx;
                timeadded += SRegEx / 60f;
                TCS.UsedTime += timeadded;
                var logs = Instantiate(StoreValues, new Vector3(0, transform.position.y, 0), transform.rotation, ViewportContent.transform);
                logs.GetComponent<AddedTimesScript>().MinutesToAdd = timeadded;
            }
            else if (!Multiple)
            {
                float timeadded = 0;
                timeadded += float.Parse(TMP.text, CultureInfo.InvariantCulture.NumberFormat);
                TCS.UsedTime += timeadded;
                var logs = Instantiate(StoreValues, new Vector3(0, transform.position.y, 0), transform.rotation, ViewportContent.transform);
                logs.GetComponent<AddedTimesScript>().MinutesToAdd = timeadded;
                logs.GetComponent<AddedTimesScript>().BeingMade = true;
                if (timeadded == 0)
                {
                    TCS.Save(TCS.Profile);
                }
            }
            if (!TCS.KeepTimeInAddBox)
            {
                TMP.text = "";
            }
        }
        catch (Exception e)
        {
            { if (TMP.text != "") { TMP.text = "INVALID"; InvaldidReset = 360; Debug.Log(e); } }
            Debug.Log(e);

        }
    }
}
